/**
 * Error code constants.
 * Standard error codes used across the application.
 * All codes use UPPER_SNAKE_CASE convention.
 */

// Authentication & Authorization
export const ErrorCodes = {
  // Auth errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOTP: 'INVALID_TOTP',
  TOTP_REQUIRED: 'TOTP_REQUIRED',
  TOTP_ALREADY_ENABLED: 'TOTP_ALREADY_ENABLED',
  TOTP_NOT_ENABLED: 'TOTP_NOT_ENABLED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',

  // Resource not found
  NOT_FOUND: 'NOT_FOUND',
  SERVER_NOT_FOUND: 'SERVER_NOT_FOUND',
  DEPLOYMENT_NOT_FOUND: 'DEPLOYMENT_NOT_FOUND',
  APP_NOT_FOUND: 'APP_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  MOUNT_NOT_FOUND: 'MOUNT_NOT_FOUND',
  CERTIFICATE_NOT_FOUND: 'CERTIFICATE_NOT_FOUND',
  SECRET_NOT_FOUND: 'SECRET_NOT_FOUND',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFIG_VALIDATION_ERROR: 'CONFIG_VALIDATION_ERROR',
  INVALID_CONFIG: 'INVALID_CONFIG',
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_STATE: 'INVALID_STATE',

  // Conflict/Duplicate errors
  CONFLICT: 'CONFLICT',
  SERVER_EXISTS: 'SERVER_EXISTS',
  DEPLOYMENT_EXISTS: 'DEPLOYMENT_EXISTS',
  USER_EXISTS: 'USER_EXISTS',
  MOUNT_EXISTS: 'MOUNT_EXISTS',
  MOUNT_POINT_EXISTS: 'MOUNT_POINT_EXISTS',
  CERTIFICATE_EXISTS: 'CERTIFICATE_EXISTS',

  // Business logic errors
  CANNOT_DELETE_CORE: 'CANNOT_DELETE_CORE',
  CANNOT_MODIFY_CORE: 'CANNOT_MODIFY_CORE',
  CANNOT_DELETE_SELF: 'CANNOT_DELETE_SELF',
  MANDATORY_APP: 'MANDATORY_APP',
  MOUNT_IN_USE: 'MOUNT_IN_USE',
  DEPENDENCY_MISSING: 'DEPENDENCY_MISSING',
  OPERATION_IN_PROGRESS: 'OPERATION_IN_PROGRESS',

  // Agent/Connection errors
  AGENT_NOT_CONNECTED: 'AGENT_NOT_CONNECTED',
  AGENT_DISCONNECTED: 'AGENT_DISCONNECTED',
  COMMAND_TIMEOUT: 'COMMAND_TIMEOUT',
  COMMAND_FAILED: 'COMMAND_FAILED',

  // System/Internal errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  CADDY_UPDATE_FAILED: 'CADDY_UPDATE_FAILED',
  BACKUP_FAILED: 'BACKUP_FAILED',
  RESTORE_FAILED: 'RESTORE_FAILED',

  // Certificate errors
  CERTIFICATE_EXPIRED: 'CERTIFICATE_EXPIRED',
  CERTIFICATE_REVOKED: 'CERTIFICATE_REVOKED',
  CA_NOT_INITIALIZED: 'CA_NOT_INITIALIZED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/**
 * Map of error codes to their default HTTP status codes.
 */
export const ErrorStatusCodes: Record<ErrorCode, number> = {
  // 401 Unauthorized
  [ErrorCodes.UNAUTHORIZED]: 401,
  [ErrorCodes.INVALID_CREDENTIALS]: 401,
  [ErrorCodes.INVALID_TOKEN]: 401,
  [ErrorCodes.TOKEN_EXPIRED]: 401,
  [ErrorCodes.INVALID_TOTP]: 401,
  [ErrorCodes.TOTP_REQUIRED]: 401,

  // 403 Forbidden
  [ErrorCodes.FORBIDDEN]: 403,
  [ErrorCodes.CANNOT_DELETE_CORE]: 403,
  [ErrorCodes.CANNOT_MODIFY_CORE]: 403,
  [ErrorCodes.CANNOT_DELETE_SELF]: 403,

  // 404 Not Found
  [ErrorCodes.NOT_FOUND]: 404,
  [ErrorCodes.SERVER_NOT_FOUND]: 404,
  [ErrorCodes.DEPLOYMENT_NOT_FOUND]: 404,
  [ErrorCodes.APP_NOT_FOUND]: 404,
  [ErrorCodes.USER_NOT_FOUND]: 404,
  [ErrorCodes.GROUP_NOT_FOUND]: 404,
  [ErrorCodes.MOUNT_NOT_FOUND]: 404,
  [ErrorCodes.CERTIFICATE_NOT_FOUND]: 404,
  [ErrorCodes.SECRET_NOT_FOUND]: 404,
  [ErrorCodes.SESSION_NOT_FOUND]: 404,

  // 400 Bad Request
  [ErrorCodes.VALIDATION_ERROR]: 400,
  [ErrorCodes.CONFIG_VALIDATION_ERROR]: 400,
  [ErrorCodes.INVALID_CONFIG]: 400,
  [ErrorCodes.INVALID_REQUEST]: 400,
  [ErrorCodes.INVALID_STATE]: 400,
  [ErrorCodes.TOTP_ALREADY_ENABLED]: 400,
  [ErrorCodes.TOTP_NOT_ENABLED]: 400,

  // 409 Conflict
  [ErrorCodes.CONFLICT]: 409,
  [ErrorCodes.SERVER_EXISTS]: 409,
  [ErrorCodes.DEPLOYMENT_EXISTS]: 409,
  [ErrorCodes.USER_EXISTS]: 409,
  [ErrorCodes.MOUNT_EXISTS]: 409,
  [ErrorCodes.MOUNT_POINT_EXISTS]: 409,
  [ErrorCodes.CERTIFICATE_EXISTS]: 409,

  // 422 Unprocessable Entity (business logic)
  [ErrorCodes.MANDATORY_APP]: 422,
  [ErrorCodes.MOUNT_IN_USE]: 422,
  [ErrorCodes.DEPENDENCY_MISSING]: 422,
  [ErrorCodes.OPERATION_IN_PROGRESS]: 422,
  [ErrorCodes.CERTIFICATE_EXPIRED]: 422,
  [ErrorCodes.CERTIFICATE_REVOKED]: 422,

  // 502/503 Connection errors
  [ErrorCodes.AGENT_NOT_CONNECTED]: 502,
  [ErrorCodes.AGENT_DISCONNECTED]: 502,
  [ErrorCodes.COMMAND_TIMEOUT]: 504,
  [ErrorCodes.COMMAND_FAILED]: 502,
  [ErrorCodes.SERVICE_UNAVAILABLE]: 503,
  [ErrorCodes.CA_NOT_INITIALIZED]: 503,
  [ErrorCodes.CADDY_UPDATE_FAILED]: 502,

  // 500 Internal Server Error
  [ErrorCodes.INTERNAL_ERROR]: 500,
  [ErrorCodes.DATABASE_ERROR]: 500,
  [ErrorCodes.BACKUP_FAILED]: 500,
  [ErrorCodes.RESTORE_FAILED]: 500,
};
